# Generated by Django 4.2.2 on 2023-06-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='votest_to_skip',
            new_name='votes_to_skip',
        ),
    ]
